##set up R env
install.packages("rmarkdown")
install.packages("remotes")
install.packages("gridExtra")
install.packages("BiocManager")
install.packages("ggfortify")
install.packages("ggrepel")
install.packages("ggplot2")
install.packages("pheatmap")
install.packages("caret")
install.packages("tidyr")
install.packages("dplyr")

#library(BiocManager)
#BiocManager::install("EnsDb.Hsapiens.v86")
#BiocManager::install("org.Hs.eg.db")
#BiocManager::install("DESeq2")
#BiocManager::install("tximport")
#BiocManager::install("tximportData")

library(remotes)
remotes::install_github("rstudio/reticulate")
remotes::install_github("karthik/wesanderson")
remotes::install_github("PNNL-CompBio/amlresistancenetworks")
