---
title: "Figure 4-5 Candidates signatures from LOO cross validation"
author: "Sara Gosline"
date: "02/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(amlresistancenetworks)
library(wesanderson)
source("../beatAMLdata.R")

pal<-wes_palette("Darjeeling1")
if(!exists('dataLoaded')){
  loadBeatAMLData()
  #loadUnNormPhosData()
  dataLoaded=TRUE
}


```

Now let's load the full models to assess signatures

```{r build sigs,warning=F,message=F}

tr.dat<- pat.data%>%
  left_join(rename(pat.phos,`AML sample`='Sample',Phosphosite='LogFoldChange'))

if(exists('combinedPreds.rds')){
  all.preds<-readRDS('combinedPreds.rds')
}else{
  eval.list<-list(
    combo=list(mf=c('Gene','Gene','Gene','site'),
               fn=c('mRNALevels','proteinLevels','binaryMutations','Phosphosite')),
    mRNA=c('Gene','mRNALevels'),
    prot=c("Gene","proteinLevels"),
    mut=c('Gene','binaryMutations'),
    phosph=c('site','Phosphosite'))

    message("Comparing logistic preds")
  
    log.reg.preds<-purrr::map_df(eval.list,
                             ~ drugMolLogReg(auc.dat,
                                                tr.dat,
                                               mol.feature=.x[1],
                                                            mol.feature.name=.x[2],
                                              category='Condition'))

      
  message('Running lasso')
    ##now train model on AML and eval on depmap data
  reg.preds<-purrr::map_df(eval.list,
                         ~ amlresistancenetworks::drugMolRegression(auc.dat,
                            tr.dat,
                            mol.feature=.x[1],
                            mol.feature.name=.x[2],                                                   
                                                 category='Condition'))
  message("Running elastic net")
  enet.reg.preds<-purrr::map_df(eval.list,
                         ~ drugMolRegression(auc.dat,
                            tr.dat,
                             mol.feature=.x[1],
                                mol.feature.name=.x[2],
                                                 category='Condition',doEnet=TRUE))
  
  
  
  e.results<-enet.reg.preds%>%
    mutate(method='ElasticNet')
 
  full.results<-reg.preds%>%
    mutate(method='LASSO')

  lr.results<-log.reg.preds%>%
    mutate(method='LogisticReg')%>%
    mutate(MSE=MSE*10000)
  
  #full.results<-rbind(full.results,lr.results)
  saveRDS(full.results,'fulllassoRegPreds.rds')
  saveRDS(lr.results,'fulllogRegPreds.rds')
  saveRDS(e.results,'fullenetRegPreds.rds')
#  saveRDS(full.results,'mostlyCompletePredictions.rds')
  
  all.res<-rbind(full.results,lr.results,e.results)
  all.preds<-rbind(enet.preds,log.preds,reg.preds)
  saveRDS(all.preds,'combinedPreds.rds')
  }
#readRDS('combinedKfoldRes.rds')
#log.preds<-readRDS('logRegPreds.rds')

```

## Evaluate GO enrichment of all signatures

From the predictions we can select those results that have the _best_ response, and plot those below. 

```{r lasso preds,warning=FALSE,echo=FALSE}


#'
#'selectDataMatAndPlot matches the output of a predictor (new.results) to the AUC data
#'and original molecular data to create heatmap
#'and combines ith with the specified data type and passes along a method to be used
#'@param drugName
#'@param meth
#'@param data
#'@return output of prediction
selectDataMatAndPlot<-function(drugName,method,data,genes,doEnrich=FALSE){
 
  #get dimensionality-reduced samples
  if(data%in%c('proteinLevels','mRNALevels','geneMutations','binaryMutations') &&!is.null(pat.data)){
    data.mat<-pat.data%>%dplyr::rename(value=data,Sample='AML sample')
 # else if(data=='Latent Variable'&&!is.null(lv.df))
#    data.mat<-lv.df%>%dplyr::rename(Gene='Latent_Variable',Sample='AML_sample',value='Loading')
#  else if(data=='KinaseExpr'&&!is.null(pat.kin))
#    data.mat<-pat.kin%>%dplyr::select(Gene='Kinase',Sample,value='meanLFC')
  }else if(data=='Phosphosite'&&!is.null(pat.phos)){
    data.mat<-pat.phos%>%dplyr::select(Gene='site',Sample,value='LogFoldChange')
#  }else if(data=='proteomicNetworkDistance'&&!is.null(prot.nets))
#    data.mat<-prot.nets%>%dplyr::select(Gene='Community',value='distance',Sample=`AML sample`)
#  else if(data=='mutationNetworkDistances' && !is.null(mut.nets))
#    data.mat<-mut.nets%>%dplyr::select(Gene='Community',value='distance',Sample=`AML sample`)
  }else{
    print(paste("Do not have data for",data))
    return(NULL)
  }
  
  auc.d<-auc.dat%>%
    dplyr::select(-c(medAUC,percAUC,overallSurvival,ageAtDiagnosis,family))%>%
    dplyr::rename(Sample='AML sample')

  #genes=getFeaturesFromString(genelist,data)
  clusterSingleDrugEfficacy(drugName,method,data,doEnrich=doEnrich,
                              this.auc.dat=auc.d,auc.thresh=100,
                            genes,data.mat)%>%
    subset(p.adjust<0.05)  
}

  #reg.preds<<-reg.preds
  new.results<-all.preds%>%
        select(-c(MSE,testMSE,corVal,numFeatures,numSamples))%>%
      rowwise()%>%
      mutate(genelist=list(getFeaturesFromString(genes,Molecular)))%>%
      select(-genes)%>%pivot_wider(names_from=Molecular,values_from=genelist)%>%
    rowwise()%>%
    mutate(mRNALevels=list(unique(unlist(mRNALevels))),proteinLevels=list(unique(unlist(proteinLevels))),
           binaryMutations=list(unique(unlist(binaryMutations))),Phosphosite=list(unique(unlist(Phosphosite))))%>%
    select(-"mRNALevels;proteinLevels;binaryMutations;Phosphosite")%>%
    pivot_longer(c(3,4,5,6),names_to='data',values_to='genes')%>%
      rowwise()%>%
    mutate(enrich=paste(selectDataMatAndPlot(compound,method,data,genes,doEnrich=TRUE)$Description,collapse=','))
  

  
DT::datatable(new.results)

##now get summary stats as well

sum.stats<-all.preds%>%
  select(-c(MSE,testMSE,numSamples))%>%
  group_by(compound,Molecular,method,genes)%>%summarize(meanCor=mean(corVal))%>%
  arrange(desc(meanCor))

DT::datatable(sum.stats)
```

## Networks from results?

For trametinib and quizartinib, let's focus on building networks to refine the predictors a bit.

```{r build selected networks}

##first select drug/model/combos
combos<-sum.stats%>%
  subset(compound%in%c('Trametinib (GSK1120212)','Quizartinib (AC220)'))%>%
  subset(meanCor>0.2)%>%
  subset(Molecular=='proteinLevels')

```


