---
title: "Figure 2-3 Candidates signatures from LOO cross validation"
author: "Sara Gosline"
date: "02/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(amlresistancenetworks)
library(wesanderson)
library(DT)

source("../beatAMLdata.R")

pal<-wes_palette("Darjeeling1")
if(!exists('dataLoaded')){
  loadBeatAMLData()
  #loadUnNormPhosData()
  dataLoaded=TRUE
}

##assumes figure 2 was already generated!!!!
syn<-synapseLogin()
all.preds<-readRDS(syn$get('')$path)
#reg.preds<-subset(all.preds,)
#log.preds<-readRDS('logRegPredsFam.rds')

```

## Best signatures from LASSO

From the predictions we can select those results that have the _best_ response, and plot those below. 

```{r lasso preds,warning=FALSE,echo=FALSE, message=FALSE}


#'
#'selectDataMatAndPlot matches the output of a predictor (new.results) to the AUC data
#'and original molecular data to create heatmap
#'and combines ith with the specified data type and passes along a method to be used
#'@param drugName
#'@param meth
#'@param data
#'@return output of prediction
selectDataMatAndPlot<-function(drugName,method,data,genelist,doEnrich=FALSE,isDrug=TRUE){
  #get dimensionality-reduced samples
  if(data%in%c('proteinLevels','mRNALevels','geneMutations','binaryMutations') &&!is.null(pat.data))
    data.mat<-pat.data%>%dplyr::rename(value=data,Sample='AML sample')
  else if(data=='Latent Variable'&&!is.null(lv.df))
    data.mat<-lv.df%>%dplyr::rename(Gene='Latent_Variable',Sample='AML_sample',value='Loading')
  else if(data=='KinaseExpr'&&!is.null(pat.kin))
    data.mat<-pat.kin%>%dplyr::select(Gene='Kinase',Sample,value='meanLFC')
  else if(data=='Phosphosite'&&!is.null(pat.phos)){
    data.mat<-pat.phos%>%dplyr::select(Gene='site',Sample,value='LogFoldChange')
  }else if(data=='proteomicNetworkDistance'&&!is.null(prot.nets))
    data.mat<-prot.nets%>%dplyr::select(Gene='Community',value='distance',Sample=`AML sample`)
#  else if(data=='mutationNetworkDistances' && !is.null(mut.nets))
#    data.mat<-mut.nets%>%dplyr::select(Gene='Community',value='distance',Sample=`AML sample`)
  else{
    print(paste("Do not have data for",data))
    return(NULL)
  }
      genes=getFeaturesFromString(genelist,data)

  if(isDrug){## we're predicting by drug not family
    auc.d<-auc.dat%>%
      dplyr::select(-c(medAUC,percAUC,overallSurvival,ageAtDiagnosis))%>%
      dplyr::rename(Sample='AML sample')
     
  clusterSingleDrugEfficacy(drugName=drugName,meth=method,data=data,doEnrich=doEnrich,
                              this.auc.dat=auc.d,auc.thresh=100,
                            genes=genes,data.mat=data.mat)%>%
    subset(p.adjust<0.05)  
  }else{
    auc.d <- auc.dat.fam%>%
      #mutate(Sample=paste(`AML sample`,Condition))%>%
      dplyr::select(-c(medAUC,percAUC,overallSurvival,ageAtDiagnosis))%>%
      dplyr::rename(Sample='AML sample')#%>%
      #dplyr::rename(Condition='family')
    
     clusterDrugFamilyEfficacy(familyName=drugName,meth=method,data=data,doEnrich=doEnrich,
                              this.auc.dat=auc.d,auc.thresh=100,
                            genes=genes,data.mat=data.mat)%>%
    subset(p.adjust<0.05)  
  }
 # print(auc.d)
 
}

  #reg.preds<<-reg.preds
  new.results<-reg.preds%>%subset(numFeatures>2)%>%#subset(MSE<1500)%>%  
    mutate(method='LASSO',doEnrich=TRUE,isDrug=FALSE)%>%
    dplyr::rename(genelist='genes')%>%
   rowwise()%>%
    mutate(enrich=paste(selectDataMatAndPlot(var,method,Molecular,genelist,doEnrich,isDrug)$Description,collapse=','))%>%
    rowwise()%>%
    mutate(features=paste(getFeaturesFromString(genelist,Molecular),collapse=','))%>%
    dplyr::select(Drug='var',MSE,features,dataType='Molecular',enrich)%>%
    arrange(MSE)

  
  DT::datatable(new.results)
```

## best signatures for logistic resgression

You can also embed plots, for example:

```{r logr preds, echo=FALSE, warning=FALSE,message=FALSE}

  other.results<-log.preds%>%subset(numFeatures>2)%>%#subset(MSE<0.21)%>%  
    mutate(method='LogisticRegression',doEnrich=TRUE,isDrug=FALSE)%>%
    dplyr::rename(genelist='genes')%>%
   rowwise()%>%
   mutate(enrich=paste(selectDataMatAndPlot(var,method,Molecular,genelist,doEnrich,isDrug)$Description,
                       collapse=','))%>%
    rowwise()%>%
    mutate(features=paste(getFeaturesFromString(genelist,Molecular),collapse=','))%>%
    dplyr::select(Drug='var',MSE,features,dataType='Molecular',enrich)%>%
  arrange(MSE)

require(DT)
DT::datatable(other.results)
full.results<-rbind(mutate(new.results,Model='LASSO'),
                    mutate(other.results,Model='Logistic'))

write.csv(full.results,'supp_table2 _allSigs.csv')

```


