---
title: "Figure 4 Performance in Cell Lines"
author: "Sara Gosline"
date: "11/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("../beatAMLdata.R")
library(amlresistancenetworks)
library(wesanderson)
if(!exists('dataLoaded')){
  loadBeatAMLData()
  dataLoaded=TRUE
}


pal<-wes_palette('Darjeeling1')
syn=synapseLogin()

## get depmap
cells<-syn$tableQuery('select distinct Sample from  syn23004114 where ( LogFoldChange<>0 AND transcriptCounts<>0)')$asDataFrame()$Sample
all.cells<-syn$tableQuery('select distinct Sample from syn23674921 where ( LogFoldChange<>0 AND transcriptCounts<>0)')$asDataFrame()$Sample

#cl.mol.dat<-syn$tableQuery('select * from syn23674921')$asDataFrame()%>%
cl.mol.dat<-syn$tableQuery('select * from syn23004114')$asDataFrame()%>%
# subset(Sample%in%all.cells)%>%
  subset(Sample%in%cells)%>%
  dplyr::rename(mRNALevels='transcriptCounts',proteinLevels='LogFoldChange')%>%
  mutate(geneMutations=numMuts/max(numMuts))%>%
  mutate(Sample=unlist(Sample),Gene=unlist(Gene))%>%
  rowwise()%>%
  mutate(binaryMutations=ifelse(numMuts==0,0,1))%>%
        mutate(binaryMutations=tidyr::replace_na(binaryMutations,0))


#create manual mapping from AML to cell Line
drug.mapping <- syn$tableQuery('select * from syn23193914 where PTRC is not NULL')$asDataFrame()

##now match the drugs between cl and tumors
cl.auc.dat<-syn$tableQuery('select * from syn23680639')$asDataFrame()%>%
  subset(Metric=='auc')%>%
  subset(Condition%in%drug.mapping$drugName)%>%
  mutate(drugName=unlist(Condition),Sample=unlist(Sample))%>%
  left_join(drug.mapping,by=c('drugName','source'))%>%
  dplyr::select(Sample,Condition='PTRC',Value,source)%>%
  subset(Sample%in%cl.mol.dat$Sample)%>%
  group_by(Sample,Condition,source)%>%summarize(Value=mean(Value))%>%ungroup()

sanger.cl.auc<-cl.auc.dat%>%
  subset(source=='Sanger')%>%
  mutate(AUC=(Value*100+50))

ctrp.cl.auc<-cl.auc.dat%>%
  subset(source=='CTRP')%>%
  mutate(AUC=Value*10)

#res<-cl.mol.dat%>%group_by(Sample)%>%
#  summarize(proteins=any(proteinLevels>0),RNA=any(mRNALevels>0),mutations=any(geneMutations>0))

  full.drg<-cl.auc.dat%>%
      select(Sample,Drug='Condition',source)%>%
    distinct()%>%
    group_by(Drug,source)%>%
    summarize(`Cell Lines`=n_distinct(Sample))%>%
  pivot_wider(names_from=source,values_from=`Cell Lines`,values_fill=list(`Cell Lines`=0))

              
  knitr::kable(full.drg)
  write.csv(full.drg,'table4.csv')
```

## Rebuild new signatures using all data 

Just to be sure we are getting the most out of the patient data we can then build signatures out of all the data and assess their performance on cell line data.

```{r build predictors, echo=FALSE,warning=FALSE}


print("Comparing Elastic Net preds")
if(file.exists('cellLineElasticRegPreds.rds')){
  enet.reg.preds<-readRDS('cellLineElasticRegPreds.rds')

}else{
  
    eval.list<-list(
    combo=list(mf=c('Gene','Gene','Gene'),
              fn=c('mRNALevels','proteinLevels','binaryMutations')),
    mRNA=c('Gene','mRNALevels'),
    prot=c("Gene","proteinLevels"),
    mut=c('Gene','binaryMutations'))
   # phosph=c('site','Phosphosite'))

  ##now train model on AML and eval on depmap data
  enet.reg.preds<-purrr::map_df(eval.list,
                         ~ drugMolRegressionEval(auc.dat,
                                                 pat.data,
                                                   mol.feature=.x[1],
                            mol.feature.name=.x[2],   
                                                 ctrp.cl.auc,
                                                 cl.mol.dat,
                                                 category='Condition',doEnet=TRUE))


  ##now do the same for Sanger
##now train model on AML and eval on depmap data
enet.sang.reg.preds<-purrr::map_df(eval.list,
                              ~ drugMolRegressionEval(auc.dat,
                                pat.data,
                                  mol.feature=.x[1],
                            mol.feature.name=.x[2],   
                                sanger.cl.auc,
                                cl.mol.dat,
                              category='Condition'))

enet.reg.preds<-rbind(mutate(enet.reg.preds,dataset='CTRP'),
                  mutate(enet.sang.reg.preds,dataset='Sanger'))
saveRDS(enet.reg.preds,'cellLineElasticRegPreds.rds')
}

print("Comparing LASSO preds")
if(file.exists('cellLinelassoRegPreds.rds')){
  lreg.preds<-readRDS('cellLinelassoRegPreds.rds')

}else{
  
    eval.list<-list(
    combo=list(mf=c('Gene','Gene','Gene'),
              fn=c('mRNALevels','proteinLevels','binaryMutations')),
    mRNA=c('Gene','mRNALevels'),
    prot=c("Gene","proteinLevels"),
    mut=c('Gene','binaryMutations'))
   # phosph=c('site','Phosphosite'))

  ##now train model on AML and eval on depmap data
  reg.preds<-purrr::map_df(eval.list,
                         ~ drugMolRegressionEval(auc.dat,
                                                 pat.data,
                                                   mol.feature=.x[1],
                            mol.feature.name=.x[2],   
                                                 ctrp.cl.auc,
                                                 cl.mol.dat,
                                                 category='Condition'))


  ##now do the same for Sanger
##now train model on AML and eval on depmap data
sang.reg.preds<-purrr::map_df(eval.list,
                              ~ drugMolRegressionEval(auc.dat,
                                pat.data,
                                  mol.feature=.x[1],
                            mol.feature.name=.x[2],   
                                sanger.cl.auc,
                                cl.mol.dat,
                              category='Condition'))

lreg.preds<-rbind(mutate(reg.preds,dataset='CTRP'),
                  mutate(sang.reg.preds,dataset='Sanger'))
saveRDS(lreg.preds,'cellLinelassoRegPreds.rds')
}

if(file.exists('cellLinelogRegPreds.rds')){
  logr.preds<-readRDS('cellLinelogRegPreds.rds')
}else{
  
  
  print("Comparing logistic preds")
  log.reg.preds<-purrr::map_df(eval.list,
                             ~ drugMolLogRegEval(auc.dat,
                                                pat.data,
                                                  mol.feature=.x[1],
                                        mol.feature.name=.x[2],   
                                               ctrp.cl.auc,
                                               cl.mol.dat,
                                               category='Condition'))


  sang.log.reg.preds<-purrr::map_df(eval.list,
                                  ~drugMolLogRegEval(auc.dat,
                                                    pat.data,
                                                      mol.feature=.x[1],
                                          mol.feature.name=.x[2],   
                                                    sanger.cl.auc,
                                                    cl.mol.dat,
                                                    category='Condition'))

logr.preds<-rbind(mutate(log.reg.preds,dataset='CTRP'),
                  mutate(sang.log.reg.preds,dataset='Sanger'))

  
  ##save both predictions to file
  saveRDS(logr.preds,'cellLinelogRegPreds.rds')
    
}

  ##now let's summarize how many predictors we have for each drug
  l.sum.tab<-logr.preds%>%subset(numFeatures>1)%>%
    group_by(Molecular,dataset)%>%
    summarize(Drugs=n_distinct(compound), Error=mean(MSE),`Mean R`=mean(corVal,na.rm=T))%>%
    mutate(Model='Logistic')
  
  enet.tab<-enet.reg.preds%>%subset(numFeatures>1)%>%
    group_by(Molecular,dataset)%>%
    summarize(Drugs=n_distinct(compound),Error=mean(MSE),`Mean R`=mean(corVal,na.rm=T))%>%
    mutate(Model='Elastic')
  
  sum.tab<-lreg.preds%>%subset(numFeatures>1)%>%
    group_by(Molecular,dataset)%>%
    summarize(Drugs=n_distinct(compound),Error=mean(MSE),`Mean R`=mean(corVal,na.rm=T))%>%
    mutate(Model='LASSO')%>%
    rbind(l.sum.tab)%>%
    rbind(enet.tab)
  
  knitr::kable(sum.tab)
  write.csv(sum.tab,file='table3_cellLineperf.csv')

```

## Evaluate predictor response


```{r cell line  performance, echo=FALSE, warning=FALSE}

library(ggplot2)
  
p1<-logr.preds%>%subset(numFeatures>0)%>%
  ggplot(aes(y=MSE,x=Molecular,fill=Molecular))+
          geom_boxplot(aes(alpha=0.8))+
          geom_jitter(aes(color=Molecular,size=numFeatures))+
  scale_color_manual(values=pal)+
scale_fill_manual(values=pal)+
  #  scale_fill_viridis_d()+
  #scale_color_viridis_d()+
  facet_grid(~dataset)+
  ggtitle("Logistic Cell Line Regression Predictor Performance")
print(p1)

p2<-lreg.preds%>%subset(numFeatures>0)%>%
  ggplot(aes(y=MSE,x=Molecular,fill=Molecular))+
          geom_boxplot(aes(alpha=0.5))+
          geom_jitter(aes(color=Molecular,size=numFeatures))+
  scale_color_manual(values=pal)+
scale_fill_manual(values=pal)+
  facet_grid(~dataset)+
  ggtitle("LASSO Cell Line Regression Predictor Performance")
print(p2)

p4<-enet.reg.preds%>%subset(numFeatures>0)%>%
  ggplot(aes(y=MSE,x=Molecular,fill=Molecular))+
          geom_boxplot(aes(alpha=0.5))+
          geom_jitter(aes(color=Molecular,size=numFeatures))+
  scale_color_manual(values=pal)+
scale_fill_manual(values=pal)+
  facet_grid(~dataset)+
  ggtitle("ElasticNet Cell Line Regression Predictor Performance")
print(p4)

p3<-logr.preds%>%mutate(Model='Logistic')%>%
  rbind(mutate(lreg.preds,Model='LASSO'))%>%
  rbind(mutate(enet.reg.preds,Model='Elastic'))%>%
  subset(numFeatures>0)%>%
    ggplot(aes(y=corVal,x=Molecular,fill=Molecular))+
          geom_boxplot(aes(alpha=0.5))+
          geom_jitter(aes(color=Molecular))+
  scale_color_manual(values=pal)+
scale_fill_manual(values=pal)+
  facet_grid(Model~dataset)+
    ggtitle("Combined Cell Line Predictor Performance")


print(p3)
ggsave('fig4a_cl_logistic.pdf',p1)
ggsave('fig4b_cl_lasso.pdf',p2)
ggsave('fig4c_cl_enet.pdf',p2)
ggsave('fig4_cl_full.pdf',p3)



```


Now we have the basic predictive models from AML to cell line data